booking:
  property: Gateway Profile Dev Profile

server:
  port: 8080

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**

        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/customers/**

        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/accounts/**

        - id: ms-card
          uri: lb://ms-card
          predicates:
            - Path=/cards/**

        - id: ms-credit
          uri: lb://ms-credit
          predicates:
            - Path=/credits/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: myVerySecretKeyForJwtAuthentication123456789
  expiration: 3600000