booking:
  property: Profile Card Dev Profile

spring:
  application:
    name: ms-card
  data:
    mongodb:
      uri: mongodb://localhost:27017/carddb
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: card-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"

app:
  kafka:
    topics:
      account-created: account-created

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7084