booking:
  property: Customer Profile Dev Profile

spring:
  application:
    name: ms-customer
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 7082
